Blog: Add Chef integration article
cobbler/cobbler.github.io pull request #184
Opened 2024-07-05 08:51 UTC by SchoolGuy

Fixes #169

2025-08-11 09:14 UTC, SchoolGuy commented
I have rebased the branch and added the old article to our blog. I will attempt to work on the new version this week.

2026-02-17 14:19 UTC, SchoolGuy commented
During my work on the blog article, I am hitting numerous bugs that I will need to fix to progress. This makes progress slow.

2026-02-19 16:20 UTC, SchoolGuy commented
After a lot of trial and error, I have a first setup that works without any manual interaction. This draft is not the final blog article. There is a lot to do before this can be considered consumable by the general public.

2026-02-23 17:05 UTC, tomschr requested changes
Some ideas for tomorrow and for further discussions. 😉

2026-02-23 17:05 UTC, tomschr commented on _posts/2012/2012-03-26-cobbler-on-centos.md
> +```
Make this an ordered list (=procedure). However, I see a problem here:

* I counted more than 16 steps.
* As a rule of thumb, you shouldn't have more than 10 steps.

In your case, I would recommend to group your steps into specific topics ("Pre-setup", "Configuration", or whatever you think is useful here). For Markdown use just a sub-header.

I would suggest:

1. Start with a sub-header.
1. Collect all steps you want to describe there.
1. Add `1.` in front of each step.
1. Start the step with a verb (you have that already).
1. Add a colon after the sentence (that introduces your code).
1. Indent the code.
1. Rinse and repeat. 😉

2026-02-23 17:05 UTC, tomschr commented on _posts/2012/2012-03-26-cobbler-on-centos.md
> +Fix Authentication For The Web Interface.
Is "For the Web Interface" a special name? If not, use lowercase:

```suggestion
Fix Authentication for the Web interface.
```

2026-02-23 17:05 UTC, tomschr commented on _posts/2012/2012-03-26-cobbler-on-centos.md
> +Set the Server Name.
Apart from spelling, I would mention what exactly the user should have to do:

```suggestion
Set the server name by replacing `cobbler.example.com` with your real server name:
```

2026-02-23 17:05 UTC, tomschr commented on _posts/2012/2012-03-26-cobbler-on-centos.md
> +Fire cobblerd up.
A more neutral way would be:


```suggestion
Start the cobblerd daemon:
```

2026-02-23 17:05 UTC, tomschr commented on _posts/2012/2012-03-26-cobbler-on-centos.md
> +Although we’re not running dhcpd on this server but I find it answers well to fill this out regardless.
That sounds a bit strange.

2026-02-23 17:05 UTC, tomschr commented on _posts/2012/2012-03-26-cobbler-on-centos.md
> +```
Does that belong to the last step? Or do you want to add an additional explanation?

2026-02-23 17:05 UTC, tomschr commented on _posts/2012/2012-03-26-cobbler-on-centos.md
> +I also use cobbler to bootstrap chef. Drop it at `/var/lib/cobbler/snippets/chef-bootstrap`
Capitalize Chef:

```suggestion
I also use cobbler to bootstrap Chef. Drop it at `/var/lib/cobbler/snippets/chef-bootstrap`
```

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +based can be found [here](https://github.com/cobbler/cobbler-web). For the purposes of this blog entry, the screenshots
I find this "here" problematic. It works well for HTML, but as soon as you print it, the information is lost: Where is "here"?

I would recommend to give a hint ("GitHUb") and add an abbreviated URL like this:

```suggestion
based can be found on the GitHub repo [cobbler/cobbler-web](https://github.com/cobbler/cobbler-web). For the purposes of this blog entry, the screenshots
```

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +of Cobbler use the built-in authentication system, which defaults to a default login of "cobbler" / "cobbler". It is
What does `"cobbler" / "cobbler"` actually mean? Is this the login name and the passphrase?

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +is strongly recommended to change this as well.
How? Is there a specific command to change the default passphrase?

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +purpose. To feed it the required data, please install them with the following command:
Remove filler word "please":


```suggestion
purpose. To feed it the required data, install them with the following command:
```

I'm still unsure what refers to "them".

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +upstreamed.
"fully upstreamed"? Do you mean this:


```suggestion
The `kickstart_start` & `kickstart_done` templates are now called `autoinstall_start` & `autoinstall_done` and are fully maintained
in the upstream repo.
```

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +Installing Chef Workstation on openSUSE Leap 15.6:
Isn't that a bit old? No 16.0? 😉

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +The following modifications need to be done to the template found at `/var/lib/cobbler/templates/sample.ks`:
Is there something missing? It seems the second sentence is a repetition of the first.

2026-02-23 17:05 UTC, tomschr commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +[^1]: <https://web.archive.org/web/20140221232937/http://blog.milford.io/2012/03/getting-a-basic-cobbler-server-going-on-centos/>
Perhaps write a conclusion or summary what the user did and what he should see?

2026-02-24 08:40 UTC, SchoolGuy commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +Installing Chef Workstation on openSUSE Leap 15.6:
You are absolutely right, but Cobbler 3.3.7 sadly doesn't work with 16.0 atm. I need to release 3.3.8 with a fix for that. As such, my choice is to go with the old version. ;)

2026-02-24 08:41 UTC, SchoolGuy commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +of Cobbler use the built-in authentication system, which defaults to a default login of "cobbler" / "cobbler". It is
Yes. I will correct this with a force push in a few minutes.

2026-02-24 08:42 UTC, SchoolGuy commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +is strongly recommended to change this as well.
Yes. Let's add it.

2026-02-24 08:43 UTC, SchoolGuy commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +The following modifications need to be done to the template found at `/var/lib/cobbler/templates/sample.ks`:
Right again. I will fix it. The edit should be visible in a few minutes.

2026-02-24 08:49 UTC, SchoolGuy commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +[^1]: <https://web.archive.org/web/20140221232937/http://blog.milford.io/2012/03/getting-a-basic-cobbler-server-going-on-centos/>
That is a good idea. Proposal for this will be visible soon as well.

2026-02-24 14:25 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +based can be found on the GitHub repo [cobbler/cobbler-web](https://github.com/cobbler/cobbler-web). For the purposes of this blog entry, the screenshots
Nitpick: Angular-based needs a dash (or could be "based on Angular")

2026-02-24 14:25 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +```
Should include a zypper ref

2026-02-24 14:25 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +of Cobbler use the built-in authentication system, which defaults to a default "cobbler" for both username and password.
Nitpick: I think leaving out the second "default" sounds a lot better
`which defaults to "cobbler" for both username and password` is perfectly fine

2026-02-24 14:25 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +- Adjust the `dynamic-bootp` option in line 25.
Linking to line numbers is probably not a good idea, maybe add a code snippet with the relevant lines and context

2026-02-24 14:25 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +in the upstream repo.
Nitpick: "have been renamed to" or "have been replaced by" would be a bit clearer

2026-02-24 14:25 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +- Line 56: Add `libxcrypt-compat` and `chef` inside the `%packages` section
Again "hardcoded" line numbers

2026-02-24 14:25 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +root@chef-workstation:~$ cd chef-repo
In other code snippets you used example values but here you used placeholder attributes in brackets, maybe decide on one or the other

2026-02-25 09:49 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +Edit `yumgen.py` line 62 and replace it with the following content:
There is still one line reference

2026-02-25 09:49 UTC, tiltingpenguin commented on _posts/2026/2026-01-28-cobbler-and-chef.md
> +  # auth  --useshadow  --enablemd5
maybe make clear that it is being disabled by commenting out the line, the # can easily be missed

2026-02-25 13:13 UTC, tiltingpenguin approved these changes

2026-02-25 13:14 UTC, merged